#!/bin/sh

set -e

echo "Running Pint..."
./vendor/bin/sail php ./vendor/bin/pint --test

echo "Running PHPStan..."
./vendor/bin/sail php ./vendor/bin/phpstan analyse

echo "Running tests..."
./vendor/bin/sail artisan test

echo "Pre-commit checks passed."
